[package]
name = "xtask"
version.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
anyhow.workspace = true
chrono.workspace = true
serde_json.workspace = true
desktop-services = { path = "../../crates/desktop-services" }
serde.workspace = true
build-tools = { path = "../build-tools" }

[dev-dependencies]
base64 = "0.22"
ed25519-dalek = { version = "2.1", features = ["pkcs8"] }
tempfile = "3"
